name: flutter_component
description: A Flutter component plugin.
version: 1.1.3
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  timeline_tile: ^2.0.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  sprintf: ^6.0.0
  hive: ^2.2.3
  package_info_plus: ^1.4.3
  device_info_plus: ^4.0.1
  url_launcher: ^6.1.5
  launch_review: ^3.0.1
  connectivity_plus: ^2.3.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.skyqi.flutter_component
        pluginClass: FlutterComponentPlugin
      ios:
        pluginClass: FlutterComponentPlugin

